site_name: Proyecto de Software
extra_javascript:
  - js/server-link.js
extra_css:
  - css/server-link.css
theme:
  name: "material"
  logo: images/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Inicio: index.md
  - Guías:
      - Comandos: guias/01_commands.md
      - Ssh: guias/02_ssh.md
      - Ssh Gitlab: guias/03_ssh_gitlab.md
      - Instalar Git: guias/04_instalar_git.md
      - Instalar Python: guias/05_instalar_python.md
      - Merge Requests en Gitlab: guias/06_merge_request.md
      - Guías de Estilo: guias/07_guias_de_estilo.md
markdown_extensions:
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - codehilite
  - def_list
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - mkdocs-video
