site_name: Proyecto de Software
extra_javascript:
  - js/server-link.js
extra_css:
  - css/server-link.css
theme:
  language: es
  name: "material"
  logo: images/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Inicio: index.md
  - Infraestructura: infraestructura.md
  - Explicaciones Prácticas: explicaciones.md
  - Blog:
      - blog/index.md
  - API:
      - api/index.html
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
  - md_in_html
  - admonition
  - codehilite
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - sane_lists
plugins:
  - blog
  - search
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.catedras.linti.unlp.edu.ar/proyecto-2025/
    - icon: fontawesome/brands/discord
      link: "https://discord.gg/m9yay6fk3g"
    - icon: fontawesome/solid/book
      link: "https://catedras.linti.unlp.edu.ar/course/view.php?id=1293"
    - icon: fontawesome/solid/envelope
      link: "mailto:proyecto@info.unlp.edu.ar"
