FORMAT: 1A
HOST: https://admin-grupoXX.proyecto2023.unlp.edu.ar

# Documentación API a implementar
Documentación online de la api a realizar en el trabajo integrador de la materia
*Projecto de Software* de la **UNLP**.

## Buscador de Servicios
En esta documentación describiremos los endpoints que creemos que son escenciales
para la implementación correcta de la aplicación.

Estos endpionts serán implementados en la _**aplicación privada**_ que les solicitamos
y consultados/usados desde la _**aplicación pública**_.

::: note
## Nota
Recordá que estos endpoints son los mínimos que nos imaginamos desde la cátedra
como necesarios.

Si dentro del grupo o el doncente asignado consideran que es necesario agregar
algún otro debido a la particularidades de la solución elegida deberán agregarlos.
:::

# Data Structures

## InstitucionData
+ name: `Institución #1` (string) - Nombre de la Institución.
+ information: `Información adicional` (string) - Información de la Institución.
+ address: `Calle 50 N° 1234` (string) - Dirección de la Institución.
+ location: `latitude, longitude` (string) - Nombre de persona a cargo de la misma.
+ web: `www.institucion1.com` (string) - Web de la Institución.
+ days_and_opening_hours: `Lunes a viernes de 8 a 18hs` (string) - Días y horarios de atención.
+ email: `info@institution.com` (string) - Información de contacto.
+ enabled: false (boolean) - Habilitado SI o NO.

## InstitucionListData
+ data: (array[InstitucionData]) - Lista de intituciones.
+ page: `1` (number) - Número de página actual.
+ per_page: `10` (number) - Cantidad de elementos por página.
+ total: `25` (number) - Total de elementos en la lista.

## RequestData
+ title: a title (string) - Título de la solicitud.
+ creation_date: `2023-10-10` (string) - Fecha de creación de la solicitud (generada por sistema).
+ close_date: `2023-12-11` (string) - Fecha de finalización de la solicitud (generada por sistema).
+ status: created (string) - Estado de la solicitud.
+ description: a long description (string) - Descripción de la solicitud.

# RequestListData
+ data: (array[RequestData]) - Lista de solicitudes.
+ page: 1 (number) - Número de página actual.
+ per_page: 10 (number) - Cantidad de elementos por página.
+ total: 25 (number) - Total de elementos en la lista.

## ServiceData
+ name: name (string) - Nombre del servicio.
+ description: a description (string) - Descripción del servicio.
+ laboratory: laboratory name (string) - Nombre del Laboratorio que presta el servicio.
+ keywords: a list of keywords (string) - Lista de palabras clave.
+ enabled: false (boolean) - Servicio habilitado SI o NO.

## ServiceListData
+ data: (array[ServiceData]) - Lista de servicios.
+ page: 1 (number) - Número de página actual.
+ per_page: 10 (number) - Cantidad de elementos por página.
+ total: 25 (number) - Total de elementos en la lista.

## DocTypeData (enum)
+ `DNI`
+ `Libreta Cívica`
+ `Libreta de Enrolamiento`

## GenderData (enum)
+ `Masculino`
+ `Femenino`
+ `Otros (Por favor especifica)`
+ `Prefiero no decir`

## PerfilData
+ user: usarname (string) - Nombre de usuario.
+ email: username@mail.com (string) - Correco electrónico.
+ number: 2560 (string) - Número de socio.
+ document_type (DocTypeData) - Tipo de documento.
+ document_number: 35.555.555 (string) - Número de documento.
+ gender (GenderData) - Género.
+ gender_other: transgénero (string) - Género no listado.
+ address: 120 y 50 (string) - Dirección.
+ phone: 221 1212-123 (string) - Teléfono.

# Group Autenticación

## Login [/api/auth]

Se requiere de un token de acceso para acceder a los endpoints de información
de socio.

### Obtener token [POST]

Permite obtener el un JSON Web Token válido para el usuario y password.

**Información del endpoint**

<i class="fa fa-times"></i> Requiere autenticación

+ Request (application/json)
    + Attributes
        + user: `john.doe@mail.com` (string, required) - User email address
        + password: `QXR0mi38a2` (string, required) - User password

+ Response 200 (application/json)
    + Attributes
        + token: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9....` (string) - JSON Web Token.

# Group Instituciones

## Información de las Instituciones [/api/institutions]

### Obtiene todas las Instituciones de la entidad [GET]

Obtiene todas las Instituciones que se realizan en la entidad.

**Información del endpoint**

<i class="fa fa-times"></i> Requiere autenticación

+ Parameters
  + page (integer, optional) - Número de página actual (predeterminado: 1).
  + per_page (integer, optional) - Cantidad de elementos por página (predeterminado: valor de configuración).

+ Response 200 (application/json)
    + Attributes (InstitucionListData)

# Group Información asociada a usuario

## Información de perfil [/api/me/profile]

### Obtener información del usuario logeado [GET]

Obtiene toda la información del perfil del usuario autenticado.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación
+ Request (application/json)
    + Headers

            Authorization: JWT <token>

+ Response 200 (application/json)
    + Attributes (PerfilData)
    
## Listado de solicitudes de servicio realizadas por el usuario logueado [/api/me/requests]

### Obtiene el listado de solicitudes del usuario logueado [GET]

Obtiene el listado de solicitudes realizadas por el usuario autenticado.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación

+ Parameters
  + page (integer, optional) - Número de página actual (predeterminado: 1).
  + per_page (integer, optional) - Cantidad de elementos por página (predeterminado: valor de configuración).

+ Request (application/json)
    + Headers

            Authorization: JWT <token>

+ Response 200 (application/json)
    + Attributes (RequestListData)


# Group Solicitudes de Servicio

## Listado de solicitudes de servicio realizadas [/api/requests]

### Obtiene el listado de solicitudes [GET]

Obtiene el listado de solicitudes realizadas por el usuario autenticado.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación

+ Request
    + Headers

            Authorization: JWT <token>

+ Response 200 (application/json)
    + Attributes (RequestListData)

## Obtiene la solicitud de servicio [/api/requests/{id}]

+ Parameters
    + id - Id de la solicitud de servicio.

### Obtiene la solicitud de servicio [GET]

Obtiene la solicitud realizada por el usuario autenticado.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación

+ Request (application/json)
    + Headers

            Authorization: JWT <token>

+ Response 200 (application/json)
    + Attributes (RequestData)


## Carga una solicitud de servicio [/api/requests]

### Carga una solicitud de servicio [POST]

Carga una solicitud solicitud de servicio por un usuario autenticado.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación

+ Request (application/json)
    + Attributes
        + title: `a title` (string, required) - Título de la solicitud.
        + description: `a long description` (string, required) - Descripción de la solicitud.
    + Headers

            Authorization: JWT <token>

+ Response 201 (application/json)
    + Attributes (RequestData)


## Carga una nota en la solicitud de servicio [/api/requests/{id}/notes]

+ Parameters
    + id - Id de la solicitud de servicio.

### Carga una nota en la solicitud de servicio [POST]

Carga una nota en la solicitud de servicio por un usuario autenticado.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación

+ Request
    + Headers

            Authorization: JWT <token>

+ Response 200 (application/json)
    + Attributes (RequestListData)

# Group Servicios

## Listado de servicios [/api/services]

### Obtiene el listado de servicios [GET]

Obtiene el listado de servicios.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación

+ Request
    + Headers

            Authorization: JWT <token>

+ Response 200 (application/json)
    + Attributes (ServiceListData)

## Detalle del servicio [/api/services/{id}]

+ Parameters
    + id - Id del servicio.

### Obtiene el detalle del servicio [GET]

Obtiene el detalle del servicio.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación

+ Request
    + Headers

            Authorization: JWT <token>

+ Response 200 (application/json)
    + Attributes (ServiceListData)


# Group Tipos de servicios

## Listado de tipos de servicios [/api/services-types]

### Obtiene el listado de tipos de servicios [GET]

Obtiene el listado de tipos de servicios.

**Información del endpoint**

<i class="fa fa-check"></i> Requiere autenticación

+ Request
    + Headers

            Authorization: JWT <token>

+ Response 200 (application/json)
    + Attributes (ServiceListData)

# Group Busqueda

## Buscador de servicios [/api/search]

### Obtiene un listado de servicios [GET]

Obtiene un listado de tipos habilitado, filtrado por el criterio de búsqueda.

+ Parameters
  + q (required, string, query) - El término de búsqueda principal.
  + type (string, query) - El tipo de búsqueda opcional.

+ Response 200 (application/json)
    + Attributes (ServiceListData)
    
+ Response 400 (application/json)
  + Attributes (object)
      - error: Parámetros inválidos (string)